### ISSUE TITLE
Display issue

### ISSUE THREAD

**Issue by jimender2** [AU-CS-499-Spring-2020/Team-Pseudo#11]
Issue in the display function.

I get this error when I try to do Display "test" + fksjdflkj.
![image](https://user-images.githubusercontent.com/35303639/75699687-dd7fdb00-5c7e-11ea-9990-a78a48056293.png)

We also are having issues with the display function not requiring strings to be in quotes like it is supposed to be. If something is not in quotes, it must be a variable or a function.

**Comment by JSMoore98** [comment]
Yeah that part is still buggy, I haven't had time to fix it yet
