### ISSUE TITLE
If Else Loops/Nested Loops

### ISSUE THREAD

**Issue by JSMoore98** [AU-CS-499-Spring-2020/Team-Pseudo#31]
Module main()
//Show Loops Off
Declare Integer temperature
Input temperature
If (temperature <= 32) Then
Display "Its Freezing out"
Else If (temperature <= 70) Then
Display "Its cool out"
Else If (temperature <= 80) The
Display "Its just right out"
Else Then
Display "Its hot out"
End If

**Comment by jimender2** [comment]
@JSMoore98 Look at the branch that I did. It should take care of this.
https://github.com/jimender2/Team-Pseudo/tree/RedoIfStatements
