### ISSUE TITLE
If statement issue

### ISSUE THREAD

**Issue by jimender2** [AU-CS-499-Spring-2020/Team-Pseudo#5]
@JSMoore98 Take a look at this. It looks like this code will never be executed.  Can you confirm?

https://github.com/AU-CS-499-Spring-2020/Team-Pseudo/blob/b3ec058b0abedc21835f19c5375c5ce311440391/main.js#L306-L308

**Comment by JSMoore98** [comment]
Oh yeah, I meant to delete that, sorry. I deleted it from the Integer method but forgot it was in the Real method too
